version: "2"

services:
  indexer:
    image: postgres
    volumes:
      - indexer-volume:/var/lib/postgresql/data
    restart: on-failure


  storage:
    image: redis
    volumes:
      - storage-volume:/data
    restart: on-failure


  gnocchi-metricd:
    image: gnocchi
    environment:
      POSTGRESQL_USER: postgres
    build:
      context: gnocchi
    depends_on:
      - indexer
      - storage
    volumes:
      - metrics-volume:/var/lib/gnocchi
    entrypoint: /run-gnocchi.sh metricd
    restart: on-failure


  gnocchi-api:
    image: gnocchi
    environment:
      POSTGRESQL_USER: postgres
    build:
      context: gnocchi
    ports:
      - "127.0.0.1:8041:8041"
    depends_on:
      - indexer
      - storage
      - gnocchi-metricd
    volumes:
      - metrics-volume:/var/lib/gnocchi
    entrypoint: /run-gnocchi.sh api
    restart: on-failure


  grafana:
    image: gnocchixyz/grafana
    build:
      context: grafana
    environment:
      #GF_INSTALL_PLUGINS: gnocchixyz-gnocchi-datasource
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_GNOCCHI_ENDPOINT: http://gnocchi:8041
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - "3000:3000"
    depends_on:
      - gnocchi-api
    volumes:
      - grafana-volume:/var/lib/grafana
    restart: on-failure


volumes:
  metrics-volume:
  grafana-volume:
  storage-volume:
  indexer-volume:
