#!/bin/sh

hector-gnocchi -f /etc/hector/config.json -v \
	--bugzilla-url "https://bugzilla.redhat.com" \
	--bugzilla-username "$BUGZILLA_USERNAME" \
	--bugzilla-password "$BUGZILLA_PASSWORD" \
	--gnocchi-username admin \
	--gnocchi-url http://gnocchi-api:8041 > /dev/console 2>&1
